server:
  port: 10086
spring:
  application:
    name: tr-registry
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    register-with-eureka: false   # 此应用为注册中心，false：不向注册中心注册自己
    fetch-registry: false # 注册中心职责是维护服务实例，false：不检索服务。